# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#

name: yourbrand

services:
  - name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    args: "azurite-blob --loose --blobHost 0.0.0.0 -l /data"
    bindings:
      - name: blob
        port: 10000
        containerPort: 10000
        protocol: http
      - name: queue
        port: 10001
        containerPort: 10001
        protocol: http
      - name: table
        port: 10002
        containerPort: 10002
        protocol: http
    volumes:
      - source: .data/azurite
        target: /data

  - name: mssql
    image: mcr.microsoft.com/azure-sql-edge:latest
    env:
      - name: MSSQL_SA_PASSWORD
        value: P@ssw0rd
      - name: MSSQL_PID
        value: Developer
      - name: ACCEPT_EULA
        value: "Y"
    bindings:
      - port: 1433
        connectionString: Server=${host},${port};User Id=sa;Password=${env:MSSQL_SA_PASSWORD};Encrypt=false
    volumes:
      - source: .data/sql-edge
        target: /var/opt/mssql/data

  - name: redis
    image: redis
    bindings:
      - port: 6379
        connectionString: "${host}:${port}"

  - name: redis-cli
    image: redis
    args: "redis-cli -h redis MONITOR"

  - name: rabbitmq
    image: rabbitmq:3-management
    bindings:
      - name: rabbit
        port: 5672
        protocol: rabbitmq
      - name: management
        port: 15672

  - name: nginx
    image: nginx
    bindings:
      - name: http
        protocol: http
        port: 80
      - name: https
        protocol: https
        port: 443
    volumes:
      - source: nginx.conf
        target: /etc/nginx/templates/default.conf.template
      - source: certs
        target: /etc/nginx/certs

  - name: smtp4dev
    image: rnwood/smtp4dev:prerelease
    bindings:
      - name: ui
        port: 3000
        containerPort: 80
        protocol: http
      - name: smtp
        port: 25
        containerPort: 25
        protocol: smtp

  # - name: apikeys
  #   include: ApiKeys/tye.yaml

  # - name: appservice
  #   include: AppService/tye.yaml

  # - name: finance
  #   include: Finance/tye.yaml

  # - name: identityservice
  #   include: IdentityService/tye.yaml

  # - name: portal
  #   include: Portal/tye.yaml

  # - name: showroom
  #   include: Showroom/tye.yaml

  # - name: timereport
  #   include: TimeReport/tye.yaml

  # - name: worker
  #   include: Worker/tye.yaml

  - name: apikeys
    project: ApiKeys/ApiKeys/ApiKeys.csproj
    bindings:
      - protocol: https
        port: 5080

  - name: appservice
    project: AppService/WebApi/WebApi.csproj
    bindings:
      - protocol: https
        port: 5020

  - name: customers
    project: Customers/Customers/Customers.csproj
    bindings:
      - protocol: https
        port: 5090

  - name: commerce
    project: Commerce/Server/Commerce.Server.csproj
    bindings:
      - protocol: https
        port: 6001

  - name: humanresources
    project: HumanResources/HumanResources/HumanResources.csproj
    bindings:
      - protocol: https
        port: 5110

  - name: catalog
    project: Catalog/Catalog/Catalog.csproj
    bindings:
      - protocol: https
        port: 5120

  - name: orders
    project: Orders/Orders/Orders.csproj
    bindings:
      - protocol: https
        port: 5130

  - name: marketing
    project: Marketing/Marketing/Marketing.csproj
    bindings:
      - protocol: https
        port: 5140

  - name: inventory
    project: Inventory/Inventory/Inventory.csproj
    bindings:
      - protocol: https
        port: 5150

  # Start Finance

  - name: financeapp
    project: Finance/Client/Client.csproj
    bindings:
      - protocol: https
        port: 5091

  - name: accounting
    project: Finance/Accounting/Accounting/WebApi/WebApi.csproj
    bindings:
      - protocol: https
        port: 5092

  - name: accountant
    project: Finance/Accounting/Accountant/Accountant/Accountant.csproj
    bindings:
      - protocol: https
        port: 5093

  - name: transactions
    project: Finance/Transactions/Transactions/Transactions.csproj
    bindings:
      - protocol: https
        port: 5094

  - name: payments
    project: Finance/Payments/Payments/Payments.csproj
    bindings:
      - protocol: https
        port: 5095

  - name: invoicing
    project: Finance/Invoicing/Invoicing/Invoicing.csproj
    bindings:
      - protocol: https
        port: 5096

  # End Finance

  - name: documents
    project: Documents/Documents/Documents.csproj
    bindings:
      - protocol: https
        port: 5097

  - name: email
    project: EmailService/EmailService/EmailService.csproj
    bindings:
      - protocol: https
        port: 5098

  - name: messenger
    project: Messenger/Messenger/Messenger.csproj
    bindings:
      - protocol: https
        port: 5099

  - name: rotrutservice
    project: Finance/RotRutService/RotRutService/RotRutService.csproj
    bindings:
      - protocol: https
        port: 5031

  - name: identity
    project: IdentityService/IdentityService/IdentityService.csproj
    bindings:
      - protocol: https
        port: 5040

  - name: webapp
    project: Portal/Portal/Portal.csproj
    bindings:
      - protocol: https
        port: 5010

  - name: showroom
    project: Showroom/WebApi/WebApi.csproj
    bindings:
      - protocol: https
        port: 5070

  - name: timereport
    project: TimeReport/WebApi/WebApi.csproj
    bindings:
      - protocol: https
        port: 5050

  - name: notifications
    project: Notifications/Notifications/Notifications.csproj
    bindings:
      - protocol: https
        port: 5030
